### PR TITLE
BVWS-219: Change RESTConnector name to RESTBridge

### PR DESCRIPTION
**Pull request by favreau**
I apparently cannot remove the RESTConnector.cmake file. Can the project admin do it for me?

### CODE REVIEW

**Comment by tribal-tec** [comment]
git mv does not work?

**Comment by favreau** [comment]
git mv did work :) Thanks for the tip.

**Comment by eile** [comment]
+1

**Comment by eile** [comment]
When do you want to merge? Shall I rename the repo?

**Comment by favreau** [comment]
Go for it! Thanks :)

**Pull request merged**
